import streamlit as st
import requests

st.set_page_config(page_title="TinyLlama Bot Generated by Pallavi khadse", page_icon="🤖")
st.title("TinyLlama Chatbot (Offline) 🤖")

# Store messages
if "messages" not in st.session_state:
    st.session_state.messages = []

# Show old chat
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# Input
prompt = st.chat_input("Ask something...")

if prompt:
    st.session_state.messages.append({"role": "user", "content": prompt})

    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        try:
            response = requests.post(
                "http://localhost:11434/api/generate",
                json={
                    "model": "tinyllama",
                    "prompt": prompt,
                    "stream": False
                }
            )

            result = response.json()["response"]
            st.markdown(result)

        except Exception as e:
            result = f"Error: {str(e)}"
            st.markdown(result)

        st.session_state.messages.append(
            {"role": "assistant", "content": result}
        )